_EXAMPLES = [
    "examples/quick3d/antialiasing",
    "examples/quick3d/bakedlightmap",
    "examples/quick3d/customeffect",
    "examples/quick3d/customgeometry",
    "examples/quick3d/custominstancing",
    "examples/quick3d/custommaterial",
    "examples/quick3d/custommorphing",
    "examples/quick3d/customshaders",
    "examples/quick3d/dynamiccreation",
    "examples/quick3d/dynamictexture",
    "examples/quick3d/effects",
    "examples/quick3d/hellocube",
    "examples/quick3d/helloqtquick3d",
    "examples/quick3d/instancing",
    "examples/quick3d/intro",
    "examples/quick3d/lights",
    "examples/quick3d/morphing",
    "examples/quick3d/offlineshaders",
    "examples/quick3d/particles3d",
    "examples/quick3d/picking",
    "examples/quick3d/principledmaterial",
    "examples/quick3d/proceduraltexture",
    "examples/quick3d/quickball",
    "examples/quick3d/quickitems",
    "examples/quick3d/reflectionprobes",
    "examples/quick3d/runtimeloader",
    "examples/quick3d/screenspacereflections",
    "examples/quick3d/skinning",
    "examples/quick3d/submeshes",
    "examples/quick3d/view3d",
]

[
    alias(
        name = example.replace(":", "_"),
        actual = "@qtquick3d-6.4//" + example,
    )
    for example in _EXAMPLES
]
